version: "0.2"
language: en
ignorePaths:
  - go.mod
  - go.sum
  - .gitignore
  - cspell.config.yaml
words:
  - agiledragon
  - ALLCAPS
  - alllower
  - apiurl
  - boumenot
  - bufconn
  - CLUSTERDOWN
  - coverprofile
  - creasty
  - ddsource
  - Ddtags
  - Debugf
  - getsentry
  - gobeam
  - gocover
  - gomock
  - gomonkey
  - gotest
  - gotestfmt
  - gotesttools
  - grpclog
  - Infof
  - irongut
  - isgomock
  - keyvals
  - marocchino
  - mitchellh
  - mockgen
  - myhost
  - mysvc
  - mytarget
  - newhost
  - newrelic
  - nolint
  - papertrail
  - papertrailapp
  - pflag
  - pflags
  - ringbuffer
  - serialises
  - smallnest
  - sourcetype
  - stretchr
  - Syncer
  - testapp
  - testhost
  - TRYAGAIN
  - upgrader
  - varargs
  - verylongname
  - Warnf
  - zaplogger
  - Zauberhaus
