// Code generated by MockGen. DO NOT EDIT.
// Source: ./redis.go
//
// Generated by this command:
//
//	mockgen --typed --write_package_comment=false -destination=../mock/redis_logger_mock.go -source=./redis.go -package=mock
//

package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRedisLogger is a mock of RedisLogger interface.
type MockRedisLogger struct {
	ctrl     *gomock.Controller
	recorder *MockRedisLoggerMockRecorder
	isgomock struct{}
}

// MockRedisLoggerMockRecorder is the mock recorder for MockRedisLogger.
type MockRedisLoggerMockRecorder struct {
	mock *MockRedisLogger
}

// NewMockRedisLogger creates a new mock instance.
func NewMockRedisLogger(ctrl *gomock.Controller) *MockRedisLogger {
	mock := &MockRedisLogger{ctrl: ctrl}
	mock.recorder = &MockRedisLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisLogger) EXPECT() *MockRedisLoggerMockRecorder {
	return m.recorder
}

// Printf mocks base method.
func (m *MockRedisLogger) Printf(ctx context.Context, format string, v ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, format}
	for _, a := range v {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Printf", varargs...)
}

// Printf indicates an expected call of Printf.
func (mr *MockRedisLoggerMockRecorder) Printf(ctx, format any, v ...any) *MockRedisLoggerPrintfCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, format}, v...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Printf", reflect.TypeOf((*MockRedisLogger)(nil).Printf), varargs...)
	return &MockRedisLoggerPrintfCall{Call: call}
}

// MockRedisLoggerPrintfCall wrap *gomock.Call
type MockRedisLoggerPrintfCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisLoggerPrintfCall) Return() *MockRedisLoggerPrintfCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisLoggerPrintfCall) Do(f func(context.Context, string, ...any)) *MockRedisLoggerPrintfCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisLoggerPrintfCall) DoAndReturn(f func(context.Context, string, ...any)) *MockRedisLoggerPrintfCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
