// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/getsentry/sentry-go (interfaces: Transport)
//
// Generated by this command:
//
//	mockgen -package mock --typed --write_package_comment=false -destination=../mock/sentry_transport_mock.go -mock_names=Transport=MockSentryTransport github.com/getsentry/sentry-go Transport
//

package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	sentry "github.com/getsentry/sentry-go"
	gomock "go.uber.org/mock/gomock"
)

// MockSentryTransport is a mock of Transport interface.
type MockSentryTransport struct {
	ctrl     *gomock.Controller
	recorder *MockSentryTransportMockRecorder
	isgomock struct{}
}

// MockSentryTransportMockRecorder is the mock recorder for MockSentryTransport.
type MockSentryTransportMockRecorder struct {
	mock *MockSentryTransport
}

// NewMockSentryTransport creates a new mock instance.
func NewMockSentryTransport(ctrl *gomock.Controller) *MockSentryTransport {
	mock := &MockSentryTransport{ctrl: ctrl}
	mock.recorder = &MockSentryTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSentryTransport) EXPECT() *MockSentryTransportMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSentryTransport) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockSentryTransportMockRecorder) Close() *MockSentryTransportCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSentryTransport)(nil).Close))
	return &MockSentryTransportCloseCall{Call: call}
}

// MockSentryTransportCloseCall wrap *gomock.Call
type MockSentryTransportCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSentryTransportCloseCall) Return() *MockSentryTransportCloseCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSentryTransportCloseCall) Do(f func()) *MockSentryTransportCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSentryTransportCloseCall) DoAndReturn(f func()) *MockSentryTransportCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Configure mocks base method.
func (m *MockSentryTransport) Configure(options sentry.ClientOptions) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Configure", options)
}

// Configure indicates an expected call of Configure.
func (mr *MockSentryTransportMockRecorder) Configure(options any) *MockSentryTransportConfigureCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configure", reflect.TypeOf((*MockSentryTransport)(nil).Configure), options)
	return &MockSentryTransportConfigureCall{Call: call}
}

// MockSentryTransportConfigureCall wrap *gomock.Call
type MockSentryTransportConfigureCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSentryTransportConfigureCall) Return() *MockSentryTransportConfigureCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSentryTransportConfigureCall) Do(f func(sentry.ClientOptions)) *MockSentryTransportConfigureCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSentryTransportConfigureCall) DoAndReturn(f func(sentry.ClientOptions)) *MockSentryTransportConfigureCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Flush mocks base method.
func (m *MockSentryTransport) Flush(timeout time.Duration) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", timeout)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockSentryTransportMockRecorder) Flush(timeout any) *MockSentryTransportFlushCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockSentryTransport)(nil).Flush), timeout)
	return &MockSentryTransportFlushCall{Call: call}
}

// MockSentryTransportFlushCall wrap *gomock.Call
type MockSentryTransportFlushCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSentryTransportFlushCall) Return(arg0 bool) *MockSentryTransportFlushCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSentryTransportFlushCall) Do(f func(time.Duration) bool) *MockSentryTransportFlushCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSentryTransportFlushCall) DoAndReturn(f func(time.Duration) bool) *MockSentryTransportFlushCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FlushWithContext mocks base method.
func (m *MockSentryTransport) FlushWithContext(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushWithContext", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// FlushWithContext indicates an expected call of FlushWithContext.
func (mr *MockSentryTransportMockRecorder) FlushWithContext(ctx any) *MockSentryTransportFlushWithContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushWithContext", reflect.TypeOf((*MockSentryTransport)(nil).FlushWithContext), ctx)
	return &MockSentryTransportFlushWithContextCall{Call: call}
}

// MockSentryTransportFlushWithContextCall wrap *gomock.Call
type MockSentryTransportFlushWithContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSentryTransportFlushWithContextCall) Return(arg0 bool) *MockSentryTransportFlushWithContextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSentryTransportFlushWithContextCall) Do(f func(context.Context) bool) *MockSentryTransportFlushWithContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSentryTransportFlushWithContextCall) DoAndReturn(f func(context.Context) bool) *MockSentryTransportFlushWithContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendEvent mocks base method.
func (m *MockSentryTransport) SendEvent(event *sentry.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEvent", event)
}

// SendEvent indicates an expected call of SendEvent.
func (mr *MockSentryTransportMockRecorder) SendEvent(event any) *MockSentryTransportSendEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEvent", reflect.TypeOf((*MockSentryTransport)(nil).SendEvent), event)
	return &MockSentryTransportSendEventCall{Call: call}
}

// MockSentryTransportSendEventCall wrap *gomock.Call
type MockSentryTransportSendEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSentryTransportSendEventCall) Return() *MockSentryTransportSendEventCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSentryTransportSendEventCall) Do(f func(*sentry.Event)) *MockSentryTransportSendEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSentryTransportSendEventCall) DoAndReturn(f func(*sentry.Event)) *MockSentryTransportSendEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
