// Code generated by MockGen. DO NOT EDIT.
// Source: go.temporal.io/sdk/log (interfaces: Logger)
//
// Generated by this command:
//
//	mockgen -package mock --typed --write_package_comment=false -destination=../mock/temporal_logger_mock.go -mock_names=Logger=MockTemporalLogger go.temporal.io/sdk/log Logger
//

package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTemporalLogger is a mock of Logger interface.
type MockTemporalLogger struct {
	ctrl     *gomock.Controller
	recorder *MockTemporalLoggerMockRecorder
	isgomock struct{}
}

// MockTemporalLoggerMockRecorder is the mock recorder for MockTemporalLogger.
type MockTemporalLoggerMockRecorder struct {
	mock *MockTemporalLogger
}

// NewMockTemporalLogger creates a new mock instance.
func NewMockTemporalLogger(ctrl *gomock.Controller) *MockTemporalLogger {
	mock := &MockTemporalLogger{ctrl: ctrl}
	mock.recorder = &MockTemporalLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemporalLogger) EXPECT() *MockTemporalLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockTemporalLogger) Debug(msg string, keyvals ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keyvals {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockTemporalLoggerMockRecorder) Debug(msg any, keyvals ...any) *MockTemporalLoggerDebugCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keyvals...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockTemporalLogger)(nil).Debug), varargs...)
	return &MockTemporalLoggerDebugCall{Call: call}
}

// MockTemporalLoggerDebugCall wrap *gomock.Call
type MockTemporalLoggerDebugCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemporalLoggerDebugCall) Return() *MockTemporalLoggerDebugCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTemporalLoggerDebugCall) Do(f func(string, ...any)) *MockTemporalLoggerDebugCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemporalLoggerDebugCall) DoAndReturn(f func(string, ...any)) *MockTemporalLoggerDebugCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Error mocks base method.
func (m *MockTemporalLogger) Error(msg string, keyvals ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keyvals {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockTemporalLoggerMockRecorder) Error(msg any, keyvals ...any) *MockTemporalLoggerErrorCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keyvals...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockTemporalLogger)(nil).Error), varargs...)
	return &MockTemporalLoggerErrorCall{Call: call}
}

// MockTemporalLoggerErrorCall wrap *gomock.Call
type MockTemporalLoggerErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemporalLoggerErrorCall) Return() *MockTemporalLoggerErrorCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTemporalLoggerErrorCall) Do(f func(string, ...any)) *MockTemporalLoggerErrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemporalLoggerErrorCall) DoAndReturn(f func(string, ...any)) *MockTemporalLoggerErrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Info mocks base method.
func (m *MockTemporalLogger) Info(msg string, keyvals ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keyvals {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockTemporalLoggerMockRecorder) Info(msg any, keyvals ...any) *MockTemporalLoggerInfoCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keyvals...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockTemporalLogger)(nil).Info), varargs...)
	return &MockTemporalLoggerInfoCall{Call: call}
}

// MockTemporalLoggerInfoCall wrap *gomock.Call
type MockTemporalLoggerInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemporalLoggerInfoCall) Return() *MockTemporalLoggerInfoCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTemporalLoggerInfoCall) Do(f func(string, ...any)) *MockTemporalLoggerInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemporalLoggerInfoCall) DoAndReturn(f func(string, ...any)) *MockTemporalLoggerInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Warn mocks base method.
func (m *MockTemporalLogger) Warn(msg string, keyvals ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keyvals {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockTemporalLoggerMockRecorder) Warn(msg any, keyvals ...any) *MockTemporalLoggerWarnCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keyvals...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockTemporalLogger)(nil).Warn), varargs...)
	return &MockTemporalLoggerWarnCall{Call: call}
}

// MockTemporalLoggerWarnCall wrap *gomock.Call
type MockTemporalLoggerWarnCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemporalLoggerWarnCall) Return() *MockTemporalLoggerWarnCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTemporalLoggerWarnCall) Do(f func(string, ...any)) *MockTemporalLoggerWarnCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemporalLoggerWarnCall) DoAndReturn(f func(string, ...any)) *MockTemporalLoggerWarnCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
